### ISSUE TITLE
[Suggestion] AUR repo

### ISSUE THREAD

**Issue by Danrus1100** [luvth/pyrfetch#9]
So, the first release came out, and why not create a package on AUR? If you want, I can help with that, I have some experience with it

**Comment by luvth** [comment]
Stop reading my brain, I was thinking abt it but the wiki seem hard, feel free to help

**Comment by Danrus1100** [comment]
When I was looking into this topic, this video helped me a lot: https://www.youtube.com/watch?v=iUz28vbWgVw&amp;t=1285s Also try to look how I made my PKGBUILD file for walcord: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=walcord. And compare it to my build instructions from github: https://github.com/Danrus1100/walcord?tab=readme-ov-file#how-to-build-frome-source

**Comment by Danrus1100** [comment]
That's all I can do for now. I'll wake up in about 10 hours and help write PKGBUILD.

**Comment by luvth** [comment]
i cant do it rn im at a party sorry

**Comment by CoolPuppyKid** [comment]
im making a PKGBUILD rn

**Comment by CoolPuppyKid** [comment]
https://aur.archlinux.org/packages/pyrfetch-git
ladys and gentlemen we have done it :+1:

**Comment by luvth** [comment]
NICE! but, share to the AUR that im the builder / maintener and I also want the PKGBUILD asap

**Comment by CoolPuppyKid** [comment]
> NICE! but, share to the AUR that im the builder / maintener and I also want the PKGBUILD asap

this is the pkg build and ill make a comment on the page saying that you made the upstream version btw you will have to add yourself to the pkg build if you want to be listed as the maintainer of the package

```PKGBUILD
# Maintainer: coolpuppykid <neduos67@gmail.com>

pkgname="pyrfetch-git"
pkgver=1.1
pkgrel=1.1
pkgdesc="Pyrfetch is a simple and lightweight version of Neofetch Written in Python"
arch=($CARCH)
url="https://github.com/luvth/pyrfetch"
license=("GPL-3.0")
provides=(pyrfetch-git)
conflicts=(pyrfetch-git)
depends=(python python-psutil)
source=("git+https://github.com/luvth/pyrfetch.git#branch=main")
sha256sums=("SKIP")

package() {
  install -Dm755 "$srcdir/pyrfetch/pyrfetch" "$pkgdir/usr/bin/pyrfetch"
  install -Dm644 "$srcdir/pyrfetch/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
```

**Comment by luvth** [comment]
Man, like, its all good, but where is my name in the project ? i want to build a reputation so my future project can maybe become more famous and more used, but its fine, ur pkgbuild is good. Can i have atleast my name ? or my email ? raphonlinux@gmail.com

**Comment by CoolPuppyKid** [comment]
> Man, like, its all good, but where is my name in the project ? i want to build a reputation so my future project can maybe become more famous and more used, but its fine, ur pkgbuild is good. Can i have atleast my name ? or my email ? [raphonlinux@gmail.com](mailto:raphonlinux@gmail.com)

k

**Comment by luvth** [comment]
thanks, but if u want to be the main maintener u can, i will not met my project (our) die

**Comment by CoolPuppyKid** [comment]
> thanks, but if u want to be the main maintener u can, i will not met my project (our) die

on the AUR package maintainers are different from github maintainers but i think its fine

**Comment by luvth** [comment]
yeah no problems, just on the pkgbuild add my email/name, thanks so much men

**Comment by luvth** [comment]
> So, the first release came out, and why not create a package on AUR? If you want, I can help with that, I have some experience with it

Aur is out, thanks to y'all

**Comment by CoolPuppyKid** [comment]
> > So, the first release came out, and why not create a package on AUR? If you want, I can help with that, I have some experience with it
> 
> Aur is out, thanks to y'all

your added
```PKGBUILD
# Maintainer: luvth <raphonlinux@gmail.com>
```

**Comment by luvth** [comment]
> > > So, the first release came out, and why not create a package on AUR? If you want, I can help with that, I have some experience with it
> 
> > 
> 
> > Aur is out, thanks to y'all
> 
> 
> 
> your added
> 
> ```PKGBUILD
> 
> # Maintainer: luvth <raphonlinux@gmail.com>
> 
> ```

perfect, im gonna sleep now, if u want to do some requests u can, and btw in the requeriements its not python its python3, small differen but some modules dont work on python >3.X

Some pull requests and feedbacks are welcome !

**Comment by luvth** [comment]
AUR is out.
